/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utilities_Cornucopia */

#ifndef _Included_utilities_Cornucopia
#define _Included_utilities_Cornucopia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utilities_Cornucopia
 * Method:    getBasicPrimitives
 * Signature: ([FII)[F
 */
JNIEXPORT jfloatArray JNICALL Java_utilities_Cornucopia_getBasicPrimitives
  (JNIEnv *, jobject, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
