/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:teachMeTF:397121:
  //println("teachMeTF - GTextField event occured " + System.currentTimeMillis()%10000000 );
  if (event == event.GETS_FOCUS) {
    drawingMode = "teach"; 
    println("Drawing mode = "+ drawingMode); 
    myShape = new Shape();
  }
  if (event==event.DRAGGING)
  {
    println("dragging"); 
  }
} //_CODE_:teachMeTF:397121:

public void drawMeTF_change1(GTextField source, GEvent event) { //_CODE_:drawMeTF:943118:
  //println("drawMeTF - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:drawMeTF:943118:

public void teachMeButton_click1(GButton source, GEvent event) { //_CODE_:teachMeButton:665691:
  if (teachMeTF.getText() == null) {
    println("I don't know what you taught me! Please type a label first and then draw object");
  }
  else {
    myShape.setID(teachMeTF.getText()); 
    println("My shape ID = "+  myShape.getID()); 
    teachMeTF.setText(""); 
    allShapes.add(myShape); 
    drawingMode = "draw";
  }
} //_CODE_:teachMeButton:665691:

public void drawMeButton_click1(GButton source, GEvent event) { //_CODE_:drawMeButton:574185:
  println("Draw me clicked, label = " + drawMeTF.getText()); 
  if (drawMeTF.getText() == null) {
    println("Nothing to draw");
  }
  else {
    //create shape here
    //then modify pos, and add to stack, after click
    drawingMode = "drawPos"; 
    for (int i = 0; i < allShapes.size() ; i++) {
      //println("All Shapes: " + allShapes); 
      //println("Shape #: " + i + " ID: " + allShapes.get(i).getID()); 
      String ID = allShapes.get(i).getID(); 
      if (ID.equals(drawMeTF.getText())) {
        print("in If");
        Shape s = allShapes.get(i); 
        targetShape = new Shape(); 
        targetShape = s; 
        strokeWeight(1);
        //targetShape.shiftHorizontal(50); 
        //println("All Lines size: " + s.allLines.size());
      }
      else println("I don't know the shape");
    }
  }drawMeTF.setText(""); 

} //_CODE_:drawMeButton:574185:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if (frame != null)
    frame.setTitle("Apprentice AI Drawing Partner");
  teachMeTF = new GTextField(this, 15, 10, 120, 30, G4P.SCROLLBARS_NONE);
  teachMeTF.setDefaultText("Teach me!");
  teachMeTF.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  teachMeTF.setOpaque(true);
  teachMeTF.addEventHandler(this, "textfield1_change1");
  drawMeTF = new GTextField(this, 569, 10, 120, 30, G4P.SCROLLBARS_NONE);
  drawMeTF.setDefaultText("[tree]");
  drawMeTF.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  drawMeTF.setOpaque(true);
  drawMeTF.addEventHandler(this, "drawMeTF_change1");
  teachMeButton = new GButton(this, 147, 10, 80, 30);
  teachMeButton.setText("Done!");
  teachMeButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  teachMeButton.addEventHandler(this, "teachMeButton_click1");
  drawMeButton = new GButton(this, 473, 10, 80, 30);
  drawMeButton.setText("Draw me a...");
  drawMeButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  drawMeButton.addEventHandler(this, "drawMeButton_click1");
}

// Variable declarations 
// autogenerated do not edit
GTextField teachMeTF; 
GTextField drawMeTF; 
GButton teachMeButton; 
GButton drawMeButton; 

