/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Cornucopia */

#ifndef _Included_jni_Cornucopia
#define _Included_jni_Cornucopia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Cornucopia
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_Cornucopia_print
  (JNIEnv *, jobject);

/*
 * Class:     jni_Cornucopia
 * Method:    getBasicPrimitives
 * Signature: ([III)[Ljni/BasicPrimitive;
 */
JNIEXPORT jobjectArray JNICALL Java_jni_Cornucopia_getBasicPrimitives
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
